version: '3.8'
#include:
#  - ../postgre/docker-compose.yaml
services:
  syslog:
    image:           innovanon/pgrsyslog
    container_name:  syslog
    ports:
      - "0.0.0.0:514:514/udp"
      - "0.0.0.0:6514:6514"
    volumes:
      - syslog-etc:/etc/rsyslog.d:ro
      - syslog-log:/var/log:rw
    restart:         always
    depends_on:
      postgres:
        condition:   service_healthy

volumes:
  syslog-etc:
    external: true
  syslog-log:
    external: true

